# Generated by Django 3.2.5 on 2021-10-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0053_auto_20210719_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGrigo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.user')),
                ('commissione', models.FloatField(blank=True, default=0)),
                ('cf', models.TextField()),
                ('pec', models.TextField()),
                ('piva', models.TextField()),
                ('sdi', models.TextField()),
                ('split_payment', models.BooleanField(default=False)),
                ('sconto', models.FloatField(blank=True, default=0)),
                ('rappresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti', to='accountGrigo.usergrigo')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.user',),
        ),
    ]
