# Generated by Django 3.2.5 on 2021-10-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='cf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='pec',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='piva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='sdi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
