# Generated by Django 3.2.5 on 2021-10-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0002_auto_20211009_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='cf',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
