# Generated by Django 3.2.5 on 2021-10-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0003_alter_usergrigo_cf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='cf',
            field=models.TextField(blank=True, null=True),
        ),
    ]
