# Generated by Django 3.2.5 on 2021-10-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0004_alter_usergrigo_cf'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrigo',
            name='is_no_login',
            field=models.BooleanField(default=False),
        ),
    ]
