# Generated by Django 3.2.5 on 2021-11-02 14:44

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0005_usergrigo_is_no_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergrigo',
            name='is_no_login',
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='coordinate_bancarie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='denominazione',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='id_danea',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='iva',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='listino',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='phone',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='porto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='rif_ammin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='cf',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='pec',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='piva',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
