# Generated by Django 3.2.5 on 2022-01-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0006_auto_20211102_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrigo',
            name='is_rappresentante',
            field=models.BooleanField(default=False),
        ),
    ]
