# Generated by Django 3.2.5 on 2022-02-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        ('csv', '0004_auto_20210709_1043'),
        ('account', '0053_auto_20210719_1048'),
        ('order', '0113_orderevent_app'),
        ('giftcard', '0004_auto_20200902_1249'),
        ('checkout', '0034_remove_checkout_quantity'),
        ('prodottoPersonalizzato', '0002_auto_20220119_1602'),
        ('accountGrigo', '0008_userextrainfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtraInfo',
        ),
    ]
