# Generated by Django 3.2.5 on 2022-03-24 15:14

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0009_delete_userextrainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergrigo',
            old_name='phone',
            new_name='cell',
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='tel',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='vettore',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='id_danea',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
