# Generated by Django 3.2.5 on 2022-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0010_auto_20220324_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='id_danea',
            field=models.TextField(blank=True, null=True),
        ),
    ]
