# Generated by Django 3.2.5 on 2022-03-24 16:11

from django.db import migrations, models
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0012_alter_usergrigo_id_danea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='cell',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='split_payment',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='tel',
            field=saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None),
        ),
    ]
