# Generated by Django 3.2.5 on 2022-06-30 13:24

from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0013_auto_20220324_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=256, null=True, unique=True)),
                ('valore', models.FloatField()),
                ('info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Listino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=256, null=True, unique=True)),
                ('ricarico', models.FloatField()),
                ('info', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='usergrigo',
            name='commissione',
        ),
        migrations.RemoveField(
            model_name='usergrigo',
            name='iva',
        ),
        migrations.RemoveField(
            model_name='usergrigo',
            name='listino',
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='tipo_cliente',
            field=models.CharField(choices=[('A', 'Azienda'), ('P', 'Privato'), ('PA', 'Pubblica Amministrazione'), ('R', 'Agenzia Pubblicitaria'), ('D', 'Dipendente')], default='A', max_length=9),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='pagamento',
            field=models.TextField(blank=True, default='Bonifico anticipato', null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='porto',
            field=models.CharField(blank=True, choices=[('A', 'Assegnato'), ('F', 'Franco'), ('FAF', 'Franco con addebito in fattura')], default='FAF', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usergrigo',
            name='vettore',
            field=models.CharField(blank=True, choices=[('D', 'Destinatario'), ('M', 'Mittente'), ('V', 'Vettore'), ('VG', 'Vettore GLS'), ('VD', 'Vettore DHL'), ('VB', 'Vettore BRT')], default='VG', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Contatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('denominazione', models.CharField(blank=True, max_length=256)),
                ('phone', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, region=None)),
                ('rappresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contatti', to='accountGrigo.usergrigo')),
            ],
        ),
    ]
