# Generated by Django 3.2.5 on 2022-06-30 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0014_auto_20220630_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrigo',
            name='iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountGrigo.iva'),
        ),
        migrations.AddField(
            model_name='usergrigo',
            name='listino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountGrigo.listino'),
        ),
    ]
