# Generated by Django 3.2.5 on 2022-07-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import saleor.account.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountGrigo', '0015_auto_20220630_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.TextField(blank=True, null=True)),
                ('id_danea', models.TextField(blank=True, null=True, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('A', 'Azienda'), ('P', 'Privato'), ('PA', 'Pubblica Amministrazione'), ('R', 'Agenzia Pubblicitaria'), ('D', 'Dipendente')], default='A', max_length=9)),
                ('tel', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None)),
                ('cell', saleor.account.models.PossiblePhoneNumberField(blank=True, db_index=True, default='', max_length=128, null=True, region=None)),
                ('is_rappresentante', models.BooleanField(default=False)),
                ('piva', models.TextField(blank=True, null=True, unique=True)),
                ('cf', models.TextField(blank=True, null=True, unique=True)),
                ('pec', models.EmailField(blank=True, max_length=254, null=True)),
                ('sdi', models.TextField(blank=True, null=True)),
                ('rif_ammin', models.TextField(blank=True, null=True)),
                ('split_payment', models.BooleanField(default=False, null=True)),
                ('porto', models.CharField(blank=True, choices=[('A', 'Assegnato'), ('F', 'Franco'), ('FAF', 'Franco con addebito in fattura')], default='FAF', max_length=3, null=True)),
                ('vettore', models.CharField(blank=True, choices=[('D', 'Destinatario'), ('M', 'Mittente'), ('V', 'Vettore'), ('VG', 'Vettore GLS'), ('VD', 'Vettore DHL'), ('VB', 'Vettore BRT')], default='VG', max_length=2, null=True)),
                ('pagamento', models.TextField(blank=True, default='Bonifico anticipato', null=True)),
                ('coordinate_bancarie', models.TextField(blank=True, null=True)),
                ('sconto', models.FloatField(blank=True, default=0)),
                ('iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountGrigo.iva')),
                ('listino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accountGrigo.listino')),
                ('rappresentante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clienti2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
