# Generated by Django 3.2.5 on 2022-07-05 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountGrigo', '0017_alter_userextra_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrigo',
            name='user_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
