# Generated by Django 3.2.5 on 2022-07-05 17:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csv', '0004_auto_20210709_1043'),
        ('order', '0113_orderevent_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0053_auto_20210719_1048'),
        ('checkout', '0034_remove_checkout_quantity'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('giftcard', '0004_auto_20200902_1249'),
        ('wishlist', '0001_initial'),
        ('accountGrigo', '0020_auto_20220705_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserGrigo',
            new_name='UserExtra',
        ),
    ]
