# Generated by Django 3.2.5 on 2022-07-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0021_rename_usergrigo_userextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='commissione',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
