# Generated by Django 3.2.5 on 2022-07-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0022_userextra_commissione'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatto',
            old_name='rappresentante',
            new_name='utente',
        ),
    ]
