# Generated by Django 3.2.5 on 2022-07-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0023_rename_rappresentante_contatto_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listino',
            name='denominazione',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='listino',
            name='ricarico',
            field=models.FloatField(default=0),
        ),
    ]
