# Generated by Django 3.2.5 on 2022-07-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountGrigo', '0024_auto_20220723_1244'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('prodottoPersonalizzato', '0004_auto_20220628_1451'),
        ('plugins', '0008_pluginconfiguration_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=256, unique=True)),
                ('info', models.TextField(blank=True, default='')),
                ('gruppo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settori', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='TempiPersonalizzazioneSettore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ore_lavoro', models.FloatField(default=0)),
                ('personalizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempi_settore', to='prodottoPersonalizzato.personalizzazione')),
                ('settore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to='plugins.settore')),
            ],
        ),
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('scadenza', models.DateTimeField(blank=True, null=True)),
                ('titolo', models.TextField()),
                ('testo', models.TextField()),
                ('completata', models.BooleanField(default=False)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche', to='accountGrigo.userextra')),
                ('settore', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='notifiche', to='plugins.settore')),
            ],
        ),
        migrations.CreateModel(
            name='Ferie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inizio', models.DateField()),
                ('data_fine', models.DateField(default=models.DateField(), null=True)),
                ('ore', models.IntegerField(default=0)),
                ('motivazione', models.TextField(blank=True, default='')),
                ('approvate', models.BooleanField(default=False)),
                ('info', models.TextField(blank=True, default='')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferie', to='accountGrigo.userextra')),
            ],
        ),
    ]
