# Generated by Django 3.2.5 on 2022-07-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0009_ferie_notifica_settore_tempipersonalizzazionesettore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferie',
            old_name='info',
            new_name='info_approvazione',
        ),
    ]
