# Generated by Django 3.2.5 on 2022-07-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('plugins', '0010_rename_info_ferie_info_approvazione'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferie',
            name='approvate',
        ),
        migrations.RemoveField(
            model_name='ferie',
            name='data_fine',
        ),
        migrations.RemoveField(
            model_name='ferie',
            name='data_inizio',
        ),
        migrations.RemoveField(
            model_name='ferie',
            name='info_approvazione',
        ),
        migrations.RemoveField(
            model_name='ferie',
            name='motivazione',
        ),
        migrations.RemoveField(
            model_name='ferie',
            name='ore',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='completata',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='data',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='mittente',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='scadenza',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='testo',
        ),
        migrations.RemoveField(
            model_name='notifica',
            name='titolo',
        ),
        migrations.RemoveField(
            model_name='settore',
            name='denominazione',
        ),
        migrations.RemoveField(
            model_name='settore',
            name='info',
        ),
        migrations.RemoveField(
            model_name='tempipersonalizzazionesettore',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tempipersonalizzazionesettore',
            name='ore_lavoro',
        ),
        migrations.RemoveField(
            model_name='tempipersonalizzazionesettore',
            name='personalizzazione',
        ),
        migrations.AlterField(
            model_name='settore',
            name='gruppo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settori', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='tempipersonalizzazionesettore',
            name='settore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempi_personalizzazione', to='plugins.settore'),
        ),
    ]
