# Generated by Django 3.2.5 on 2022-07-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0012_auto_20220727_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settore',
            name='denominazione',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
