# Generated by Django 3.2.5 on 2021-10-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0034_remove_checkout_quantity'),
        ('product', '0146_auto_20210518_0945'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0113_orderevent_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField()),
                ('locazione', models.CharField(max_length=1)),
                ('tipo_prezzo', models.CharField(max_length=1)),
                ('prezzo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Lavorazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField()),
                ('ordine', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tessuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('composizione', models.TextField()),
                ('grammatura', models.PositiveBigIntegerField()),
                ('descrizione', models.TextField()),
                ('altezza', models.PositiveBigIntegerField()),
                ('costo_ml', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProdottoPersonalizzato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='statoLavorazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stati', to='prodottoPersonalizzato.lavorazione')),
                ('stato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavorazioni', to='prodottoPersonalizzato.stato')),
            ],
        ),
        migrations.CreateModel(
            name='Personalizzazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default='bozza')),
                ('data_scadenza', models.DateField()),
                ('misure', models.JSONField()),
                ('finiture_frontend', models.JSONField()),
                ('lavorazioni', models.JSONField()),
                ('checkout_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizzazione_checkout_line', to='checkout.checkoutline')),
                ('order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione_order_line', to='order.orderline')),
                ('personalizzazione_precedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione_sucessiva', to='prodottoPersonalizzato.personalizzazione')),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('tessuto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prodottoPersonalizzato.tessuto')),
                ('utente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileGrafico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='appena_arrivati')),
                ('anteprima', models.FileField(blank=True, null=True, upload_to='appena_arrivati')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('personalizzazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='prodottoPersonalizzato.personalizzazione')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLinePersonalizzata',
            fields=[
                ('checkoutline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkoutline')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figlio', to='prodottoPersonalizzato.checkoutlinepersonalizzata')),
            ],
            bases=('checkout.checkoutline',),
        ),
        migrations.CreateModel(
            name='AzioneLavorazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lavorazioni', to='prodottoPersonalizzato.azione')),
                ('lavorazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azioni', to='prodottoPersonalizzato.lavorazione')),
            ],
        ),
    ]
