# Generated by Django 3.2.5 on 2022-01-19 16:02

from django.db import migrations, models
import django.db.models.deletion
import saleor.plugins.grigoprint.prodottoPersonalizzato.models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0034_remove_checkout_quantity'),
        ('order', '0113_orderevent_app'),
        ('prodottoPersonalizzato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutLinePadreFiglio',
            fields=[
                ('checkoutline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkoutline')),
                ('figlio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_line_padre', to='checkout.checkoutline')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_line_figlio', to='checkout.checkoutline')),
            ],
            bases=('checkout.checkoutline',),
        ),
        migrations.CreateModel(
            name='OrderLinePadreFiglio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figlio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_padre', to='order.orderline')),
                ('padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_figlio', to='order.orderline')),
            ],
        ),
        migrations.AlterField(
            model_name='filegrafico',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=saleor.plugins.grigoprint.prodottoPersonalizzato.models.user_appena_arrivati_path),
        ),
        migrations.AlterField(
            model_name='filegrafico',
            name='nome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CheckoutLinePersonalizzata',
        ),
    ]
