# Generated by Django 3.2.5 on 2022-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodottoPersonalizzato', '0002_auto_20220119_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tessuto',
            name='spreco_ml',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='descrizione',
            field=models.TextField(blank=True, null=True),
        ),
    ]
