# Generated by Django 3.2.5 on 2022-06-28 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0146_auto_20210518_0945'),
        ('checkout', '0034_remove_checkout_quantity'),
        ('order', '0113_orderevent_app'),
        ('prodottoPersonalizzato', '0003_auto_20220324_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField()),
                ('tipo_prezzo', models.CharField(max_length=1)),
                ('prezzo_ml', models.FloatField()),
                ('tempo_realizzazione', models.PositiveSmallIntegerField()),
                ('tempo_avvio', models.PositiveSmallIntegerField()),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='foto-finiture')),
            ],
        ),
        migrations.CreateModel(
            name='FinituraDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField()),
                ('finiture', models.JSONField()),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='foto-finiture')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finiture_default', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='LineaCarrello',
            fields=[
                ('checkoutline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.checkoutline')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkout_line_figlio', to='checkout.checkoutline')),
            ],
            bases=('checkout.checkoutline',),
        ),
        migrations.CreateModel(
            name='LineaOrdine',
            fields=[
                ('orderline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.orderline')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_line_figlio', to='order.orderline')),
            ],
            bases=('order.orderline',),
        ),
        migrations.CreateModel(
            name='Particolare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('descrizione', models.TextField()),
                ('costo_cad', models.FloatField()),
                ('tempo_realizzazione', models.PositiveSmallIntegerField()),
                ('tempo_avvio', models.PositiveSmallIntegerField()),
                ('foto', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='foto-particolari')),
            ],
        ),
        migrations.CreateModel(
            name='ParticolareFinitura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('finitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particolare', to='prodottoPersonalizzato.finitura')),
                ('particolare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finitura', to='prodottoPersonalizzato.particolare')),
            ],
        ),
        migrations.RemoveField(
            model_name='azionelavorazione',
            name='azione',
        ),
        migrations.RemoveField(
            model_name='azionelavorazione',
            name='lavorazione',
        ),
        migrations.RemoveField(
            model_name='checkoutlinepadrefiglio',
            name='checkoutline_ptr',
        ),
        migrations.RemoveField(
            model_name='checkoutlinepadrefiglio',
            name='figlio',
        ),
        migrations.RemoveField(
            model_name='checkoutlinepadrefiglio',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='orderlinepadrefiglio',
            name='figlio',
        ),
        migrations.RemoveField(
            model_name='orderlinepadrefiglio',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='statolavorazione',
            name='lavorazione',
        ),
        migrations.RemoveField(
            model_name='statolavorazione',
            name='stato',
        ),
        migrations.RenameField(
            model_name='personalizzazione',
            old_name='finiture_frontend',
            new_name='finiture',
        ),
        migrations.RemoveField(
            model_name='filegrafico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='personalizzazione',
            name='lavorazioni',
        ),
        migrations.RemoveField(
            model_name='personalizzazione',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='personalizzazione',
            name='utente',
        ),
        migrations.AddField(
            model_name='personalizzazione',
            name='titolo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tessuto',
            name='velocita_calandra',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tessuto',
            name='velocita_cucitura',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tessuto',
            name='velocita_stampa',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filegrafico',
            name='personalizzazione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prodottoPersonalizzato.personalizzazione'),
        ),
        migrations.AlterField(
            model_name='filegrafico',
            name='quantita',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='checkout_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione_checkout_line', to='checkout.checkoutline'),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='personalizzazione_precedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizzazione_sucessiva', to='prodottoPersonalizzato.personalizzazione'),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='prodotto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='altezza',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='grammatura',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Azione',
        ),
        migrations.DeleteModel(
            name='AzioneLavorazione',
        ),
        migrations.DeleteModel(
            name='CheckoutLinePadreFiglio',
        ),
        migrations.DeleteModel(
            name='Lavorazione',
        ),
        migrations.DeleteModel(
            name='OrderLinePadreFiglio',
        ),
        migrations.DeleteModel(
            name='Stato',
        ),
        migrations.DeleteModel(
            name='statoLavorazione',
        ),
    ]
