# Generated by Django 3.2.5 on 2022-07-27 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0034_remove_checkout_quantity'),
        ('order', '0113_orderevent_app'),
        ('prodottoPersonalizzato', '0004_auto_20220628_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalizzazione',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='personalizzazione',
            name='log_prezzo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='finitura',
            name='nome',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='finitura',
            name='prezzo_ml',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lineacarrello',
            name='checkoutline_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extra', serialize=False, to='checkout.checkoutline'),
        ),
        migrations.AlterField(
            model_name='lineacarrello',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figlio', to='prodottoPersonalizzato.lineacarrello'),
        ),
        migrations.AlterField(
            model_name='lineaordine',
            name='orderline_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='extra', serialize=False, to='order.orderline'),
        ),
        migrations.AlterField(
            model_name='lineaordine',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figlio', to='prodottoPersonalizzato.lineaordine'),
        ),
        migrations.AlterField(
            model_name='particolare',
            name='costo_cad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='particolare',
            name='nome',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='checkout_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione_checkout_line', to='prodottoPersonalizzato.lineacarrello'),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione_order_line', to='prodottoPersonalizzato.lineaordine'),
        ),
    ]
