# Generated by Django 3.2.5 on 2022-07-27 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodottoPersonalizzato', '0005_auto_20220727_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoProdottoPersonalizzato',
        ),
        migrations.RemoveField(
            model_name='personalizzazione',
            name='checkout_line',
        ),
        migrations.RemoveField(
            model_name='personalizzazione',
            name='order_line',
        ),
        migrations.AddField(
            model_name='personalizzazione',
            name='liea_carrello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione', to='prodottoPersonalizzato.lineacarrello'),
        ),
        migrations.AddField(
            model_name='personalizzazione',
            name='liea_ordine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalizzazione', to='prodottoPersonalizzato.lineaordine'),
        ),
    ]
