# Generated by Django 3.2.5 on 2022-08-01 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prodottoPersonalizzato', '0006_auto_20220727_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalizzazione',
            old_name='liea_carrello',
            new_name='linea_carrello',
        ),
        migrations.RenameField(
            model_name='personalizzazione',
            old_name='liea_ordine',
            new_name='linea_ordine',
        ),
        migrations.RemoveField(
            model_name='tessuto',
            name='spreco_ml',
        ),
        migrations.AddField(
            model_name='particolarefinitura',
            name='misura_default',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalizzazione',
            name='nome_tessuto',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tessuto',
            name='avviamento_ml',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='particolarefinitura',
            name='finitura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particolare_finitura', to='prodottoPersonalizzato.finitura'),
        ),
        migrations.AlterField(
            model_name='particolarefinitura',
            name='particolare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particolare_finitura', to='prodottoPersonalizzato.particolare'),
        ),
        migrations.AlterField(
            model_name='personalizzazione',
            name='personalizzazione_precedente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalizzazione_successiva', to='prodottoPersonalizzato.personalizzazione'),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='composizione',
            field=models.TextField(default='100% poliestere'),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='nome',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='velocita_calandra',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='velocita_cucitura',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tessuto',
            name='velocita_stampa',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
